name: baseconverter
description: A web frontend for baseconverter
version: 1.0.0
homepage: https://baseconverter.chtison.io

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  grpc: ^0.6.1

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
  protoc_plugin: ^0.8.2
  sass_builder: ^2.0.0
